name: Generate GameMaker Project

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download UndertaleModCli
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/UnderminersTeam/UndertaleModTool/releases/download/nightly/CLI-windows-latest-Debug-isBundled-true.zip" -OutFile "cli.zip"

    - name: Run Decompiler
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path output
        .\cli\UndertaleModCli.exe load data.win
        .\cli\UndertaleModCli.exe dump --output output
        dir output

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gamemaker-project
        path: output/
